name: Release Packaging

on:
  release:
    types:
      - published # 当一个 Release 被发布时触发
permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库的代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 创建 zh_CN 文件夹并移动所有内容到其中
      - name: Prepare zh_CN folder
        run: |
          mkdir -p zh_CN
          shopt -s extglob
          mv !(zh_CN|.git) zh_CN/ || true

      # 打包为 zip 文件
      - name: Create zip archive
        run: zip -r release.zip zh_CN

      # 使用 softprops/action-gh-release 上传文件到 Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}